---
credhub_key_encryption_passwords_0/key: ((credhub_key_encryption_password))
credhub_key_encryption_passwords_0/name: encryption_key
networking_poe_ssl_certs_0/certificate: ((wildcard_cert.certificate))
networking_poe_ssl_certs_0/privatekey: ((wildcard_cert.private_key))
networking_poe_ssl_certs_0/name: wildcard_cert
uaa/service_provider_key_credentials/certificate: ((wildcard_cert.certificate))
uaa/service_provider_key_credentials/privatekey: ((wildcard_cert.private_key))
system_blobstore/external_gcs_service_account/buildpacks_bucket: ((cloud_storage_buildpacks_bucket))
system_blobstore/external_gcs_service_account/droplets_bucket: ((cloud_storage_droplets_bucket))
system_blobstore/external_gcs_service_account/packages_bucket: ((cloud_storage_packages_bucket))
system_blobstore/external_gcs_service_account/resources_bucket: ((cloud_storage_resources_bucket))
system_blobstore/external_gcs_service_account/service_account_email: ((cloud_storage_email))
system_blobstore/external_gcs_service_account/service_account_json_key: ((cloud_storage_key))
