singleton_availability_zone: us-east1-b
network_name: pas
az2_name: us-east1-c
az3_name: us-east1-d
cloud_controller/system_domain: ((pas_sys_domain))
cloud_controller/apps_domain: ((pas_apps_domain))
mysql_monitor/recipient_email: ((pas_mysql_monitor_email))
credhub_key_encryption_passwords_0/primary: true
credhub_key_encryption_passwords_0/name: primary credhub secret
credhub_key_encryption_passwords_0/key: ((pas_credhub_encryption_key.private_key))
uaa/service_provider_key_credentials/certificate: ((pas_uaa_service_provider_certificate.certificate))
uaa/service_provider_key_credentials/privatekey: ((pas_uaa_service_provider_certificate.private_key))
routing_custom_ca_certificates: ((pas_routing_custom_ca_certificate.ca))
networking_poe_ssl_certs_0/name: wildcard
networking_poe_ssl_certs_0/certificate: ((pas_wildcard_pem.certificate))
networking_poe_ssl_certs_0/privatekey: ((pas_wildcard_pem.private_key))
security_acknowledgement: X
nfsbrokerpush_post_deploy_state: false
mysql_monitor_instances: 0
secure_service_instance_credentials: true
credhub_instances: 1
haproxy_forward_tls/enable/backend_ca: ((pas_routing_custom_ca_certificate.ca))
ha_proxy_instances: 2
