resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

- name: azure-blobstore
  type: docker-image
  source:
    repository: pcfabr/azure-blobstore-resource

resources:
- name: platform-automation-tasks
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: platform-automation
    product_version: ((pcf_automation_version))
    sort_by: semver

- name: platform-automation-image
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: platform-automation
    product_version: ((pcf_automation_version))
    sort_by: semver

- name: installation
  type: azure-blobstore
  source:
    storage_account_name: ((storage_account_name))
    storage_account_key: ((storage_account_key))
    container: ((container))
    versioned_file: installation.zip

- name: state
  type: azure-blobstore
  source:
    storage_account_name: ((storage_account_name))
    storage_account_key: ((storage_account_key))
    container: ((container))
    versioned_file: state.yml

#- name: configuration
#  type: git
#  source:
#    branch: master
#    uri: git@github.com:marijenk/platform_automation.git
#    private_key: ((git_private_key.private_key))
#    paths:
#    - "environments/((iaas))/((foundation))/pipeline.yml"
#    - "environments/((iaas))/((foundation))/config"

- name: director-configuration
  type: git
  source:
    branch: master
    uri: git@github.com:marijenk/platform_automation.git
    private_key: ((git_private_key.private_key))
    paths:
    - "environments/((iaas))/((foundation))/config-director"

jobs:
- name: validate-director-configuration
  plan:
  - in_parallel:
    - get: director-configuration
      trigger: true
    - get: platform-automation-image
      params:
        globs: ["platform-automation-image-*.*"]
        unpack: true
    - get: platform-automation-tasks
      params:
        globs: ["platform-automation-tasks-*.*"]
        unpack: true

  - task: credhub-interpolate
    image: platform-automation-image
    file: platform-automation-tasks/tasks/credhub-interpolate.yml
    params: &director_credhub_interpolate_params
      CREDHUB_SERVER: ((concourse_url))
      CREDHUB_CA_CERT: ((concourse_credhub_ca.certificate))
      CREDHUB_CLIENT: concourse_to_credhub_client
      CREDHUB_SECRET: ((concourse_credhub_client_secret))
      PREFIX: '/concourse/((team))'
      INTERPOLATION_PATHS: "environments/((iaas))/((foundation))/config-director/secrets"
    input_mapping:
      files: director-configuration

- name: install-opsman
  plan:
  - in_parallel:
    - get: director-configuration
      trigger: true
      passed: ["validate-director-configuration"]
    - get: state
    - get: platform-automation-image
      params:
        globs: ["platform-automation-image-*.*"]
        unpack: true
    - get: platform-automation-tasks
      params:
        globs: ["platform-automation-tasks-*.*"]
        unpack: true

  - task: credhub-interpolate
    image: platform-automation-image
    file: platform-automation-tasks/tasks/credhub-interpolate.yml
    params: *director_credhub_interpolate_params
    input_mapping:
      files: director-configuration

  - task: download-create-opsman
    image: platform-automation-image
    file: platform-automation-tasks/tasks/create-vm.yml
    input_mapping:
      download-config: director-configuration
      state: state
      config: director-configuration
      vars: director-configuration
      secrets: interpolated-files
    params:
      DOWNLOAD_CONFIG_FILE: environments/((iaas))/((foundation))/config-director/versions/opsman.yml
      STATE_FILE: environments/((iaas))/((foundation))/state/state.yml
      OPSMAN_CONFIG_FILE: environments/((iaas))/((foundation))/config-director/templates/opsman.yml
      VARS_FILES: |
        vars/environments/azure/common-director/opsman.yml
        vars/environments/azure/sandbox/config-director/vars/infra.yml
        vars/environments/azure/sandbox/config-director/vars/opsman.yml
        secrets/environments/azure/sandbox/config-director/secrets/opsman.yml
        secrets/environments/azure/sandbox/config-director/secrets/pivnet.yml
  - put: state
    params:
      file: generated-state/state.yml


  - task: configure-authentication
    image: platform-automation-image
    file: platform-automation-tasks/tasks/configure-authentication.yml
    attempts: 20
    input_mapping:
      env: interpolated-files
      config: interpolated-files
    params:
      ENV_FILE: environments/((iaas))/((foundation))/config-director/secrets/env.yml
      AUTH_CONFIG_FILE: environments/((iaas))/((foundation))/config-director/secrets/auth.yml

  - task: configure-director
    image: platform-automation-image
    file: platform-automation-tasks/tasks/configure-director.yml
    input_mapping:
      config: director-configuration
      env: interpolated-files
      vars: director-configuration
      secrets: interpolated-files
    params:
      ENV_FILE: environments/((iaas))/((foundation))/config-director/secrets/env.yml
      DIRECTOR_CONFIG_FILE: environments/((iaas))/((foundation))/config-director/templates/director.yml
      VARS_FILES: |
        vars/environments/((iaas))/common-director/director.yml
        vars/environments/((iaas))/((foundation))/config-director/vars/infra.yml
        vars/environments/((iaas))/((foundation))/config-director/vars/director.yml
        secrets/environments/((iaas))/((foundation))/config-director/secrets/director.yml

  - task: apply-director-changes
    image: platform-automation-image
    file: platform-automation-tasks/tasks/apply-director-changes.yml
    input_mapping:
      env: interpolated-files
    params:
      ENV_FILE: environments/((iaas))/((foundation))/config-director/secrets/env.yml

- name: export-installation
  plan:
  - in_parallel:
    - get: director-configuration
      trigger: true
      passed: [ install-opsman ]
    - get: platform-automation-image
      params:
        globs: ["platform-automation-image-*.*"]
        unpack: true
    - get: platform-automation-tasks
      params:
        globs: ["platform-automation-tasks-*.*"]
        unpack: true

  - task: credhub-interpolate
    image: platform-automation-image
    file: platform-automation-tasks/tasks/credhub-interpolate.yml
    params: *director_credhub_interpolate_params
    input_mapping:
      files: director-configuration

  - task: export-installation
    image: platform-automation-image
    file: platform-automation-tasks/tasks/export-installation.yml
    input_mapping:
      env: interpolated-files
    params:
      ENV_FILE: environments/((iaas))/((foundation))/config-director/secrets/env.yml
  - put: installation
    params:
      file: installation/installation-*.zip

- name: upgrade-opsman
  plan:
  - in_parallel:
    - get: director-configuration
      trigger: true
      passed: [ export-installation ]
    - get: state
    - get: installation
      passed: [ export-installation ]
    - get: platform-automation-image
      params:
        globs: ["platform-automation-image-*.*"]
        unpack: true
    - get: platform-automation-tasks
      params:
        globs: ["platform-automation-tasks-*.*"]
        unpack: true

  - task: credhub-interpolate
    image: platform-automation-image
    file: platform-automation-tasks/tasks/credhub-interpolate.yml
    params: *director_credhub_interpolate_params
    input_mapping:
      files: director-configuration

  - task: download-upgrade-opsman
    image: platform-automation-image
    file: platform-automation-tasks/tasks/upgrade-opsman.yml
    input_mapping:
      download-config: director-configuration
      state: state
      config: director-configuration
      vars: director-configuration
      secrets: interpolated-files
      installation: installation
      env: interpolated-files
    params:
      DOWNLOAD_CONFIG_FILE: environments/((iaas))/((foundation))/config-director/versions/opsman.yml
      STATE_FILE: environments/((iaas))/((foundation))/state/state.yml
      OPSMAN_CONFIG_FILE: environments/((iaas))/((foundation))/config-director/templates/opsman.yml
      VARS_FILES: |
        vars/environments/((iaas))/common-director/opsman.yml
        vars/environments/((iaas))/((foundation))/config-director/vars/infra.yml
        vars/environments/((iaas))/((foundation))/config-director/vars/opsman.yml
        secrets/environments/((iaas))/((foundation))/config-director/secrets/opsman.yml
        secrets/environments/((iaas))/((foundation))/config-director/secrets/pivnet.yml
      ENV_FILE: environments/((iaas))/((foundation))/config-director/secrets/env.yml
  - put: state
    params:
      file: generated-state/state.yml

  - task: apply-director-changes
    image: platform-automation-image
    file: platform-automation-tasks/tasks/apply-director-changes.yml
    input_mapping:
      env: interpolated-files
    params:
      ENV_FILE: environments/((iaas))/((foundation))/config-director/secrets/env.yml
