resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: platform-automation-tasks
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: platform-automation
    product_version: ((pcf_automation_version))
    sort_by: semver

- name: platform-automation-image
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: platform-automation
    product_version: ((pcf_automation_version))
    sort_by: semver

- name: configuration
  type: git
  source:
    branch: master
    uri: git@github.com:marijenk/platform_automation.git
    private_key: ((git_private_key.private_key))
    paths:
    - "environments/((iaas))/((foundation))/pipeline.yml"
    - "environments/((iaas))/((foundation))/config"

jobs:
- name: fetch-ubuntu-xenial-250
  plan:
  - in_parallel:
    - get: configuration
      trigger: true
    - get: platform-automation-image
      params:
        globs: ["platform-automation-image-*.*"]
        unpack: true
    - get: platform-automation-tasks
      params:
        globs: ["platform-automation-tasks-*.*"]
        unpack: true

  - task: credhub-interpolate
    image: platform-automation-image
    file: platform-automation-tasks/tasks/credhub-interpolate.yml
    params: &credhub_interpolate_params
      CREDHUB_SERVER: ((concourse_url))
      CREDHUB_CA_CERT: ((concourse_credhub_ca.certificate))
      CREDHUB_CLIENT: concourse_to_credhub_client
      CREDHUB_SECRET: ((concourse_credhub_client_secret))
      PREFIX: '/concourse/((team))'
      INTERPOLATION_PATHS: environments/((iaas))/((foundation))/config/versions environments/((iaas))/((foundation))/config/secrets
    input_mapping:
      files: configuration

  - task: download-stemcell
    image: platform-automation-image
    file: platform-automation-tasks/tasks/download-product.yml
    input_mapping:
      config: interpolated-files
    params:
      CONFIG_FILE: "environments/((iaas))/((foundation))/config/versions/cf-stemcell.yml"

  - task: upload-stemcell
    image: platform-automation-image
    file: platform-automation-tasks/tasks/upload-stemcell.yml
    input_mapping:
      env: interpolated-files
      stemcell: downloaded-stemcell
    params:
      ENV_FILE: environments/((iaas))/((foundation))/config/secrets/env.yml
