errand-config:
  delete-space:
    pre-delete-state: ((delete-space_pre_delete_state))
  push-apps:
    post-deploy-state: ((push-apps_post_deploy_state))
  smoke-tests:
    post-deploy-state: ((smoke-tests_post_deploy_state))
network-properties:
  network:
    name: ((network_name))
  other_availability_zones:
  - name: ((singleton_availability_zone))
  - name: ((az2_name))
  - name: ((az3_name))
  service_network:
    name: ((service_network_name))
  singleton_availability_zone:
    name: ((singleton_availability_zone))
product-name: p-healthwatch
product-properties:
  .healthwatch-forwarder.boshhealth_instance_count:
    value: ((healthwatch-forwarder/boshhealth_instance_count))
  .healthwatch-forwarder.boshtasks_instance_count:
    value: ((healthwatch-forwarder/boshtasks_instance_count))
  .healthwatch-forwarder.canary_instance_count:
    value: ((healthwatch-forwarder/canary_instance_count))
  .healthwatch-forwarder.cli_instance_count:
    value: ((healthwatch-forwarder/cli_instance_count))
  .healthwatch-forwarder.foundation_name:
    value: ((healthwatch-forwarder/foundation_name))
  .healthwatch-forwarder.health_check_az:
    value: ((healthwatch-forwarder/health_check_az))
  .healthwatch-forwarder.ingestor_instance_count:
    value: ((healthwatch-forwarder/ingestor_instance_count))
  .healthwatch-forwarder.opsman_instance_count:
    value: ((healthwatch-forwarder/opsman_instance_count))
  .healthwatch-forwarder.publish_to_eva:
    value: ((healthwatch-forwarder/publish_to_eva))
  .healthwatch-forwarder.worker_instance_count:
    value: ((healthwatch-forwarder/worker_instance_count))
  .properties.boshtasks:
    value: enable
  .properties.boshtasks.enable.bosh_taskcheck_password:
    value:
      secret: ((boshtasks/enable/bosh_taskcheck_password))
  .properties.boshtasks.enable.bosh_taskcheck_username:
    value: ((boshtasks/enable/bosh_taskcheck_username))
  .properties.opsman:
    selected_option: disable
    value: disable
  .properties.syslog_selector:
    value: "No"
resource-config:
  healthwatch-forwarder:
    instance_type:
      id: ((healthwatch-forwarder_instance_type))
    instances: ((healthwatch-forwarder_instances))
    internet_connected: ((healthwatch-forwarder_internet_connected))
    persistent_disk:
      size_mb: ((healthwatch-forwarder_persistent_disk_size))
  mysql:
    instance_type:
      id: ((mysql_instance_type))
    instances: ((mysql_instances))
    internet_connected: ((mysql_internet_connected))
    persistent_disk:
      size_mb: ((mysql_persistent_disk_size))
  redis:
    instance_type:
      id: ((redis_instance_type))
    instances: ((redis_instances))
    internet_connected: ((redis_internet_connected))
    persistent_disk:
      size_mb: ((redis_persistent_disk_size))
