deploy-autoscaler_post_deploy_state: default
deploy-notifications-ui_post_deploy_state: default
deploy-notifications_post_deploy_state: default
metric_registrar_smoke_test_post_deploy_state: default
nfsbrokerpush_post_deploy_state: default
push-apps-manager_post_deploy_state: default
push-usage-service_post_deploy_state: default
smbbrokerpush_post_deploy_state: default
smoke_tests_post_deploy_state: default
test-autoscaling_post_deploy_state: default
backup_restore_instance_type: automatic
backup_restore_instances: automatic
backup_restore_persistent_disk_size: automatic
clock_global_instance_type: automatic
clock_global_instances: automatic
cloud_controller_instance_type: automatic
cloud_controller_instances: automatic
cloud_controller_worker_instance_type: automatic
cloud_controller_worker_instances: automatic
consul_server_instance_type: automatic
consul_server_instances: automatic
consul_server_persistent_disk_size: automatic
credhub_instance_type: automatic
credhub_instances: automatic
diego_brain_instance_type: automatic
diego_brain_instances: automatic
diego_cell_instance_type: automatic
diego_cell_instances: automatic
diego_database_instance_type: automatic
diego_database_instances: automatic
doppler_instance_type: automatic
doppler_instances: automatic
ha_proxy_instance_type: automatic
ha_proxy_instances: automatic
loggregator_trafficcontroller_instance_type: automatic
loggregator_trafficcontroller_instances: automatic
mysql_instance_type: automatic
mysql_instances: automatic
mysql_monitor_instance_type: automatic
mysql_monitor_instances: automatic
mysql_persistent_disk_size: automatic
mysql_proxy_instance_type: automatic
mysql_proxy_instances: automatic
nats_instance_type: automatic
nats_instances: automatic
nfs_server_instance_type: automatic
nfs_server_instances: automatic
nfs_server_persistent_disk_size: automatic
router_instance_type: automatic
router_instances: automatic
syslog_adapter_instance_type: automatic
syslog_adapter_instances: automatic
syslog_scheduler_instance_type: automatic
syslog_scheduler_instances: automatic
tcp_router_instance_type: automatic
tcp_router_instances: automatic
uaa_instance_type: automatic
uaa_instances: automatic
